version: "3"

services:
  mysql-dev:
    image: mysql:8.0.21
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: healthDB
    command: --init-file /data/application/init.sql
    volumes:
      - ./mysqldata:/var/lib/mysql:rw,delegated
      - ./init.sql:/data/application/init.sql
      # - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
# TODO Setup volumes
# volumes:
#   db_data:
